# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: resting-state HRF Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: Forum created in Disqus

# Your name, as you want it to appear underneath each post and in the footer
author: Guorong Wu

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: /rsHRF-Forum

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://wgrmath.github.io/rsHRF-Forum

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: rsHRFforum

# The public key for your disqus application
disqus_publickey: cVy9WcjLl6TI8EbBAL6PDy8FqMr4gm3HXXfERv7anOYHj3AZAyO2jD66Pqqe71B0
